### PR TITLE
Use count(), instead of size which forces to load the whole collection

### PR DESCRIPTION
**Pull request by blueglyph**
We may as well show good practice, and void using the implementation of count() in this particular case.
In general, count() is recommended since it may avoid loading the whole collection in memory, if implemented accordingly.

### CODE REVIEW

**Comment by blueglyph** [comment]
Please disregard the two following commits (98f343f and 7bf6e84), I saw the website was not up-to-date with the repo.

**Comment by blueglyph** [comment]
Hello?

**Comment by blueglyph** [comment]
Is this project still alive?

**Comment by svtk** [comment]
Thank you for the pull request! Why do you think that it's important to use 'count' here since for a collection 'count()' without arguments simply returns 'size'?

**Comment by blueglyph** [comment]
As I said, just for good practice. The example is illustrating a database mockup, we know `count()` will behave as desired for a real database sequence, by not loading the whole database into a temporary local collection, it will count the elements (and ideally be implemented efficiently). Besides, `size` only exists for some types.
`size` is also associated to memory size in other dialects, though that may be far-stretched, but by association people would rather use length() or count() to avoid misinterpretation.

**Pull request closed without merging**
